substitutions:
  device_name: sonoffmini
  
esphome:
  name: ${device_name}
  platform: ESP8266          #Sonoff Mini
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  

# Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#   ssid: "sonoffMini"
#   password: "12345678"
#captive_portal:


# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: wifi_signal
    name: ${device_name} Wifi Signal Strength
    update_interval: 60s


#######################################
# Device specific Config Begins Below #
#######################################


########## switches ##########

# The relay on GPIO12 is a Virtual Switch.
switch:
  - platform: gpio
    name: ${device_name}_relay
    icon: "mdi:lightbulb_outline"
    pin:
      number: 12
      mode: output
    id: relay
    restore_mode: restore_default_off
    
  - platform: gpio
    name: $(device_name)_statuslight
    pin:
      number: 16
      mode: output



########## Sensors ##########
#
# A physical switch or button to ground is a binary sensor.
#

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0                # Physical Button on the mini
      inverted: False
      mode: INPUT_PULLUP
    name: ${device_name}_button
    internal: true
    on_press:
      - switch.toggle:
          id: relay
      
  - platform: gpio
    id: switch_s2
    pin:
      number: GPIO04               # Physical Switch on terminal S2 (GPIO4)
      inverted: True
      mode: INPUT
    name: ${device_name}_switch
    

    on_press:
      then:
        - switch.toggle:
            id: relay
    on_release:
      then:
        - switch.toggle:
            id: relay



status_led:
  pin:
    number: GPIO16
    inverted: true

