# This YAML file contains code for the following:
#  Dallas DS18B20 Temperature sensor 
#  Wemos D1 Mini SSD1306 64x48 Shield (I2C) displaying:
#    Temperature


substitutions:
  display_name: temperature-1
  
esphome:
  name: ${display_name}
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:

ota:
  safe_mode: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true


#-----------------------------

### Wemos D1 Mini SSD1306 64x48 Shield (I2C) ### 
font:
  - file: "fonts/comic.ttf"
    id: my_font
    size: 25

i2c:
  sda: D2
  scl: D1
  scan: True

display:
  - platform: ssd1306_i2c
    model: "SSD1306 64x48"
    reset_pin: D3
    address: 0x3C
    lambda: |-
      it.printf(0, 25, id(my_font), TextAlign::BASELINE_LEFT , "%.1f°", id(remote).state);


### Dallas DS18B20 Temperature sensor  ###
dallas:
  - pin: D4      
    update_interval: 5s    
    
sensor:
  - platform: dallas
    address: 0x1300FF9843001628
    name: ${display_name} remote
    id: remote
    unit_of_measurement: '°F'
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;
    
  - platform: dallas
    address: 0xBD021792455EE728
    name: ${display_name} local
    id: local
    unit_of_measurement: '°F'
    filters:
    - lambda: return x * (9.0/5.0) + 32.0;

