# garage-door-v1
# This program is a prelude to the garage door opener.
# A button is on D6. When pressed, the relayon D5 closes
# for 500ms.


esphome:
  name: garage-door-v1
  platform: ESP8266
  board: d1_mini


# Multiple networks with DHCP
wifi:
  networks:
  - ssid: Kaywinnet
    password: !secret wifi_password
  - ssid: Serenity
    password: !secret serenity_password
  - ssid: Naboo
    password: !secret naboo_password


# Enable logging
logger:
  level: VERBOSE     # default is DEBUG


# Enable Home Assistant API
api:


# Enable Over the Air updates
ota:
  safe_mode: True


#Blink the LED_BuiltIn if there's a problem, on otherwise.    
status_led:
  pin:
    number: D4
    
    
text_sensor:
  # Get the WiFi details
  - platform: wifi_info
    ip_address:
      name: WemosPro IP Address
    ssid:
      name: WemosPro SSID
    mac_address:
      name: WemosPro Mac Address
  

sensor:
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: WemosPro WiFi Signal
    update_interval: 60s


##### Stuff for this board #####

#Relay or LED is connected here
switch:
  - platform: gpio
    pin: D5
    name: "garageDoorRelay" # Becomes switch.garageDoorRelay in HA
    id: garageDoor

#Button is connected to pin D6
binary_sensor:
  - platform: gpio
    pin:
      number: D6
      mode:
        input: true
        pullup: true
    name: "Garage Door Toggle Button"
    on_press:
      #Turn on the relay on D5 for a half second.
      then:
        - switch.toggle: garageDoor
        - delay: 500ms
        - switch.toggle: garageDoor

