substitutions:
  display_name: sonoffsv

esphome:
  name: ${display_name}
  platform: ESP8266
  board: esp01_1m
  
wifi:
  ssid: "Kaywinnet"
  password: !secret wifi_password
  fast_connect: true



# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# Enable Over the Air updates
ota:
  safe_mode: True
  
  
###############################
# Sonoff SV peripherals

# Virtual switch GPI12  
switch:
  - platform: gpio
    name: ${display_name} relay
    pin:
      number: 12
      mode: output
    id: relay
    
  - platform: gpio
    name: ${display_name} sled
    pin:
      number: 13
      mode: output
    id: sled
    
    
# Physical Button on GPIO0
binary_sensor:
  - platform: gpio
    pin: 
      number: 0
      inverted: False
      mode: INPUT_PULLUP
    name: ${display_name} button
    internal: true
    on_press:
      - switch.toggle: relay    
      
  # Physical Button on GPIO14  
  - platform: gpio
    pin: 
      number: 14
      inverted: True
      mode: INPUT_PULLUP
    name: ${display_name} Remote Button
    on_press:
      then:
      - switch.toggle: relay
    on_release:
      then:
      - switch.toggle: relay

      
# Get the WiFi details
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${display_name} IP Address
      id: ip
    ssid:
      name: ${display_name} SSID
    mac_address:
      name: ${display_name} Mac Address

sensor:
  - platform: wifi_signal
    name: ${display_name} WiFi Signal Sensor
    update_interval: 60s


status_led:
  pin:
    number: 13        #Green LED on SV board


